import { useState } from 'react'

const STORAGE_KEY = 'inti_disclaimer_accepted'

export function isDisclaimerAccepted(): boolean {
  return localStorage.getItem(STORAGE_KEY) === 'true'
}

interface Props {
  onAccept: () => void
}

export function DisclaimerModal({ onAccept }: Props) {
  const [checked, setChecked] = useState(false)

  function handleAccept() {
    localStorage.setItem(STORAGE_KEY, 'true')
    onAccept()
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] flex flex-col">

        {/* Header */}
        <div className="px-6 py-5 border-b border-gray-200 flex items-center gap-3 shrink-0">
          <span className="text-2xl" aria-hidden>⚠️</span>
          <h1 className="text-lg font-bold text-gray-900">Unofficial Tool Disclaimer</h1>
        </div>

        {/* Scrollable body */}
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-5 text-sm text-gray-700 leading-relaxed">
          <p>
            This software is a community-built framework intended as a starting point for further
            development — it is not a finished product and is not affiliated with, endorsed by, or
            an official offering of any company. By continuing, you acknowledge and agree to the
            following terms:
          </p>

          <section className="space-y-1">
            <h2 className="font-bold text-gray-900">No Support or Warranty</h2>
            <p>
              This framework is an independent, community-built utility. It is not supported,
              maintained, endorsed, or guaranteed by any company. All functionality is provided
              without any express or implied warranties, including but not limited to
              merchantability, fitness for a particular purpose, or non-infringement.
            </p>
          </section>

          <section className="space-y-1">
            <h2 className="font-bold text-gray-900">Development Origin</h2>
            <p>
              Portions of this framework were generated by AI coding agents operating under human
              direction. No company reviews, validates, or certifies the accuracy, security, or
              reliability of any AI-generated code included in this software.
            </p>
          </section>

          <section className="space-y-1">
            <h2 className="font-bold text-gray-900">Security &amp; Data Risks</h2>
            <p>
              Use of this framework may introduce security, privacy, or operational risks. No
              company audits or verifies the security posture of this software. You are solely
              responsible for safeguarding all credentials, including API keys, tokens, and other
              sensitive information.
            </p>
          </section>

          <section className="space-y-1">
            <h2 className="font-bold text-gray-900">No Liability</h2>
            <p>
              No company shall be liable for any damages, losses, data breaches, unauthorized
              access, service disruptions, or other adverse outcomes arising from the use of this
              framework. All usage is strictly at your own risk.
            </p>
          </section>

          <section className="space-y-1">
            <h2 className="font-bold text-gray-900">User Responsibility</h2>
            <p>
              This framework is a starting point — you are responsible for reviewing, adapting, and
              hardening it to meet your own security, compliance, and operational requirements.
              If you choose to proceed, you do so voluntarily and assume full responsibility for
              all consequences.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="px-6 py-5 border-t border-gray-200 space-y-4 shrink-0">
          <label className="flex items-start gap-3 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={checked}
              onChange={(e) => setChecked(e.target.checked)}
              className="mt-0.5 accent-brand-blue shrink-0"
            />
            <span className="text-sm text-gray-700">
              I have read, understood, and agree to these terms.
            </span>
          </label>
          <button
            onClick={handleAccept}
            disabled={!checked}
            className="w-full px-4 py-2.5 bg-brand-navy text-white rounded-lg font-semibold text-sm
                       hover:bg-brand-navy-light disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
          >
            Continue
          </button>
        </div>

      </div>
    </div>
  )
}
